/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package imageclassification.GUI;

import imageclassification.Main;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Singgi
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        ImageIcon imgbackground=new ImageIcon(getClass().getResource("/imageclassification/assets/images/background.jpg"));
        Image img= imgbackground.getImage();
        Image temp=img.getScaledInstance(646,572,Image.SCALE_SMOOTH);
        background.setIcon(new ImageIcon(temp));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image_btn = new javax.swing.JLabel();
        start_btn = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setLayout(null);

        image_btn.setBackground(new java.awt.Color(204, 204, 204));
        image_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        image_btn.setForeground(new java.awt.Color(51, 51, 51));
        image_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_btn.setText("Choose Image");
        image_btn.setOpaque(true);
        add(image_btn);
        image_btn.setBounds(200, 100, 240, 260);

        start_btn.setBackground(new java.awt.Color(204, 0, 0));
        start_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        start_btn.setForeground(new java.awt.Color(204, 204, 204));
        start_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        start_btn.setText("Start");
        start_btn.setOpaque(true);
        start_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                start_btnMouseClicked(evt);
            }
        });
        add(start_btn);
        start_btn.setBounds(227, 400, 190, 50);

        background.setText("background");
        add(background);
        background.setBounds(0, 0, 646, 572);
    }// </editor-fold>//GEN-END:initComponents

    private void start_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_start_btnMouseClicked
        Main.mainPanel.removeAll();
        Main.mainPanel.add(new Result());
        Main.mainPanel.repaint();
        Main.mainPanel.revalidate();
    }//GEN-LAST:event_start_btnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel image_btn;
    private javax.swing.JLabel start_btn;
    // End of variables declaration//GEN-END:variables
}
